import type { Metadata } from "next";
import { Playfair_Display, Ms_Madi, Geist, Inter, Qwitcher_Grypen } from "next/font/google";

import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  style: ["italic"],
  variable: "--font-playfair",
});

const msMadi = Ms_Madi({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ms-madi",
});

const geist = Geist({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ms-geist",
});

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ms-inter",
});

const qwitcherGypen = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ms-qwitcher-grypen",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={msMadi.variable}>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Ms+Madi&family=Playfair:ital,opsz,wght@0,5..1200,300..900;1,5..1200,300..900&family=Qwitcher+Grypen:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${playfair.variable} ${msMadi.variable} ${msMadi.variable} ${inter.variable} antialiased ${qwitcherGypen.variable}`}
      >
        {children}
      </body>

    </html>
  );
}
